aruco_detector_node:
  ros__parameters:
    marker_config_file: config/markers_board.yaml
    aruco_dict: DICT_6X6_250
    camera_calibration_file: config/cam_intrinsic.yaml
    camera_frame_id: usb_cam
    board_frame: board
    image_topic: /image_raw
    board_pose_topic: /localization/aruco/board_pose
    publish_tf: true
    min_markers_for_board: 1
    min_markers_to_initialize: 2
    max_position_jump_m: 0.35
    max_rotation_jump_deg: 55.0
    max_yaw_jump_deg: 40.0
    max_reprojection_rmse_px: 6.0
    debug_image_topic: /localization/aruco/debug_image

aruco_imu_eskf_localization_node:
  ros__parameters:
    board_pose_topic: /localization/aruco/board_pose
    odom_topic: /localization/relative/odom
    pose_topic: /localization/relative/pose
    board_frame: board
    base_frame: base_link
    camera_frame: usb_cam
    publish_tf: true
    base_to_imu_translation: [0.06, 0.0, 0.095]
    base_to_imu_quaternion_xyzw: [0.0, 0.0, 0.0, 1.0]
    base_to_camera_translation: [0.27, 0.0, 0.135]
    base_to_camera_quaternion_xyzw: [-0.5, 0.5, -0.5, 0.5]

pose_rviz_marker_node:
  ros__parameters:
    odom_topic: /localization/relative/odom
    marker_topic: /localization/relative/pose_markers
    marker_namespace: relative_pose_viz
    axis_line_width: 0.01
    text_size: 0.08
    vehicle_arrow_length: 0.22
    vehicle_arrow_width: 0.05
    good_cov_trace: 0.02
    warn_cov_trace: 0.12
