ublox_gps_node:
  ros__parameters:
    debug: 1
    device: /dev/ttyACM1
    frame_id: follower/follower_gps
    config_on_startup: true
    rate: 8.0
    nav_rate: 1
    dynamic_model: portable
    uart1:
      baudrate: 115200
    gnss:
      glonass: true
      beidou: true
      gps: true
      qzss: true
      galileo: true
      imes: false
    tmode3: 0
    sv_in:
      reset: false
      min_dur: 300
      acc_lim: 3.0
    inf:
      all: true
    publish:
      aid/all: false
      rxm:
        rtcm: true
